#!/bin/sh

APNIC_DELEGATED_LATEST="https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest"
GFW_LIST_URL="https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"
CHINA_IP_LIST_URL="https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt"

CUSTOM_BYPASS="
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16
fc00::/7
fe80::/10
"

CUSTOM_PROXY="
||github.com
||openai.com
"

log() {
    logger -t gen-rules "[INFO] $1"
    echo "[INFO] $1"
}

err() {
    logger -t gen-rules "[ERROR] $1"
    echo "[ERROR] $1" >&2
}

fetch_url() {
    local url="$1"
    local out="$2"
    
    if command -v curl >/dev/null 2>&1; then
        curl -k -s -f -o "$out" "$url"
    elif command -v wget >/dev/null 2>&1; then
        wget -q --no-check-certificate -O "$out" "$url"
    else
        err "wget or curl not found, cannot download data!"
        return 1
    fi
    
    if [ ! -s "$out" ]; then
        err "Download failed or file is empty: $url"
        return 1
    fi
    return 0
}

NOW=$(date +"%Y-%m-%dT%H:%M:%S")

log "Downloading remote lists..."

if ! fetch_url "$APNIC_DELEGATED_LATEST" "/tmp/apnic.txt" || \
   ! fetch_url "$GFW_LIST_URL" "/tmp/gfw.txt" || \
   ! fetch_url "$CHINA_IP_LIST_URL" "/tmp/chnroutes.txt"; then
    err "Network error or download failed. Update aborted! Existing rules are preserved."
    rm -f /tmp/apnic.txt /tmp/gfw.txt /tmp/chnroutes.txt
    exit 1
fi

log "Download and verification successful. Generating new rules..."

log "Generating temporary IPSet files..."
echo "define chnip4 = {" > chnip4.ips.tmp
awk -F '|' -v first=1 '
    /^#/ || NF<7 { next }
    $1 == "apnic" && $2 == "CN" && $3 == "ipv4" {
        if (!first) printf ",\n";
        first = 0;
        mask = 32 - (log($5) / log(2));
        printf "    %s/%d", $4, mask;
    }
    END { print "\n}" }
' /tmp/apnic.txt >> chnip4.ips.tmp

echo "define chnip6 = {" > chnip6.ips.tmp
awk -F '|' -v first=1 '
    /^#/ || NF<7 { next }
    $1 == "apnic" && $2 == "CN" && $3 == "ipv6" {
        if (!first) printf ",\n";
        first = 0;
        printf "    %s/%d", $4, $5;
    }
    END { print "\n}" }
' /tmp/apnic.txt >> chnip6.ips.tmp

log "Generating temporary ACL files..."
cat <<EOF > shadowproxy-redir.acl.tmp
# Generated by shell script for redir.acl
# Time: $NOW

[proxy_all]

[bypass_list]
EOF
echo "$CUSTOM_BYPASS" | awk 'NF {print}' >> shadowproxy-redir.acl.tmp
echo "" >> shadowproxy-redir.acl.tmp
echo "[bypass_list]" >> shadowproxy-redir.acl.tmp
awk '/^[^#]/ && NF {print}' /tmp/chnroutes.txt >> shadowproxy-redir.acl.tmp

cat <<EOF > shadowproxy-dns-base.acl.tmp
# Generated by shell script for dns-base.acl
# Time: $NOW

[bypass_all]

[bypass_list]
EOF
echo "$CUSTOM_BYPASS" | awk 'NF {print}' >> shadowproxy-dns-base.acl.tmp
cat <<EOF >> shadowproxy-dns-base.acl.tmp

[proxy_list]
{proxy_domains}

[proxy_list]
EOF
echo "$CUSTOM_PROXY" | awk 'NF {print}' >> shadowproxy-dns-base.acl.tmp
awk '/^[^#]/ && NF {print "||" $0}' /tmp/gfw.txt >> shadowproxy-dns-base.acl.tmp
echo "" >> shadowproxy-dns-base.acl.tmp
echo "[bypass_list]" >> shadowproxy-dns-base.acl.tmp
awk '/^[^#]/ && NF {print}' /tmp/chnroutes.txt >> shadowproxy-dns-base.acl.tmp

log "Generation complete. Replacing old files..."
mv -f chnip4.ips.tmp chnip4.ips
mv -f chnip6.ips.tmp chnip6.ips
mv -f shadowproxy-redir.acl.tmp shadowproxy-redir.acl
mv -f shadowproxy-dns-base.acl.tmp shadowproxy-dns-base.acl

rm -f /tmp/apnic.txt /tmp/gfw.txt /tmp/chnroutes.txt

log "Update process finished successfully!"
