#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import sys
import logging
import argparse
from urllib import request
from datetime import datetime

# ================= 基礎設定 =================
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

# ================= 最佳化資料來源 URL =================
APNIC_DELEGATED_LATEST = "https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest"

# 使用高頻更新的純文字 GFW 列表
GFW_LIST_URL = "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"

# 使用高頻更新的精準中國 IP 列表
CHINA_IP_LIST_URL = "https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt"

# ================= 自定義規則 =================
CUSTOM_BYPASS = [
    "127.0.0.1",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "fd00::/8",
]

# 自定義強制代理網域 (使用官方推薦的 ABP 語法)
CUSTOM_PROXY = [
    "||github.com",
    "||openai.com"
]

# ================= 共用功能 =================
def fetch_url_text(url):
    logger.info(f"正在下載資料: {url}")
    try:
        req = request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with request.urlopen(req, timeout=15) as response:
            return response.read().decode('utf-8')
    except Exception as e:
        logger.error(f"無法獲取 {url}，錯誤訊息: {e}")
        sys.exit(1)

# ================= APNIC IPSet 生成邏輯 =================
def generate_ipset(content, name, location_set, type_set, output_file):
    cidr_trans = {2 ** (32 - i - 1): i + 1 for i in range(32)} if 'ipv4' in type_set else {}
    output_file.write(f"define {name} = {{\n")
    first_entry = True  

    for line in content.splitlines():
        if line.startswith('#') or not line.strip():
            continue

        splits = line.split('|')
        if len(splits) == 7:
            registry, cc, type_, start, value, _, _ = splits
            if registry == 'apnic' and cc in location_set and type_ in type_set:
                if type_ == 'ipv4':
                    mask = cidr_trans[int(value)]
                    cidr = f"{start}/{mask}"
                elif type_ == 'ipv6':
                    cidr = f"{start}/{value}"
                
                if not first_entry:
                    output_file.write(",\n")
                first_entry = False
                output_file.write(f"    {cidr}")
    output_file.write("\n}\n")

# ================= ACL 規則生成邏輯 =================
def generate_acl_files():
    # 1. 獲取 GFW 名單，並為每個網域加上官方推薦的 '||' 前綴
    gfw_text = fetch_url_text(GFW_LIST_URL)
    gfw_list = [f"||{line.strip()}" for line in gfw_text.splitlines() if line.strip() and not line.startswith('#')]
    
    # 加入自定義代理網域
    gfw_list = CUSTOM_PROXY + gfw_list
    
    # 2. 獲取中國 IP 名單
    china_ip_text = fetch_url_text(CHINA_IP_LIST_URL)
    china_ips = [line.strip() for line in china_ip_text.splitlines() if line.strip() and not line.startswith('#')]
    
    now_str = datetime.now().isoformat()

    # --- 生成 shadowproxy-redir.acl ---
    logger.info("正在生成 shadowproxy-redir.acl")
    with open("shadowproxy-redir.acl", "w", encoding="utf-8") as fp:
        fp.write("# Generated by merged script for redir.acl\n")
        fp.write(f"# Time: {now_str}\n\n")
        fp.write("[proxy_all]\n\n")
        fp.write("[bypass_list]\n")
        fp.write("\n".join(china_ips) + "\n\n")
        fp.write("[bypass_list]\n")
        fp.write("\n".join(CUSTOM_BYPASS) + "\n")

    # --- 生成 shadowproxy-dns-base.acl ---
    logger.info("正在生成 shadowproxy-dns-base.acl")
    with open("shadowproxy-dns-base.acl", "w", encoding="utf-8") as fp:
        fp.write("# Generated by merged script for dns-base.acl\n")
        fp.write(f"# Time: {now_str}\n\n")
        fp.write("[bypass_all]\n\n")
        fp.write("[proxy_list]\n")
        fp.write("{proxy_domains}\n\n")
        fp.write("[proxy_list]\n")
        fp.write("\n".join(gfw_list) + "\n\n")
        fp.write("[bypass_list]\n")
        fp.write("\n".join(china_ips) + "\n\n")
        fp.write("[bypass_list]\n")
        fp.write("\n".join(CUSTOM_BYPASS) + "\n")

# ================= 主程式執行區 =================
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="一次生成 APNIC IPSets 與 Shadowproxy ACLs 文件")
    parser.add_argument('--name', '-n', help='IPSet 名稱', type=str, required=False)
    parser.add_argument('--location', '-l', help='過濾的國家代碼 (例如 CN)', nargs='+', type=str, required=False)
    parser.add_argument('--address-type', '-t', help='IP 類型 (ipv4 或 ipv6)', nargs='+', type=str, required=False, choices=['ipv4', 'ipv6'])
    parser.add_argument('--output', '-o', help='IPSet 的輸出文件', type=str, required=False)

    args = parser.parse_args()

    if not any(vars(args).values()):
        logger.info("未提供參數，啟動預設全自動生成模式...")
        apnic_data = fetch_url_text(APNIC_DELEGATED_LATEST)
        
        logger.info("正在生成 chnip4.ips")
        with open("chnip4.ips", "w", encoding="utf-8") as fp4:
            generate_ipset(apnic_data, "chnip4", {"CN"}, {"ipv4"}, fp4)
            
        logger.info("正在生成 chnip6.ips")
        with open("chnip6.ips", "w", encoding="utf-8") as fp6:
            generate_ipset(apnic_data, "chnip6", {"CN"}, {"ipv6"}, fp6)
            
        generate_acl_files()
        logger.info("所有文件均已成功生成！")
    else:
        name = args.name or "custom_ip"
        location_set = set(args.location) if args.location else {"CN"}
        type_set = set(args.address_type) if args.address_type else {"ipv4", "ipv6"}
        apnic_data = fetch_url_text(APNIC_DELEGATED_LATEST)

        if args.output:
            with open(args.output, 'w', encoding="utf-8") as fp:
                generate_ipset(apnic_data, name, location_set, type_set, fp)
            logger.info(f"成功生成客製化文件: {args.output}")
        else:
            generate_ipset(apnic_data, name, location_set, type_set, sys.stdout)
