#!/bin/sh /etc/rc.common
#
# Copyright (C) 2014-2023 King <9566618@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90
STOP=15

USE_PROCD=1

NAME=shadowproxy

CONF_DIR=/etc/$NAME
TPROXY_PORT=60080
DNS_PORT=5300
SERVER_LIST_V4=""
SERVER_LIST_V6=""
ENABLED="$(uci -q get shadowproxy.@main[0].enabled)"

uci_load "$NAME"

_info() {
  logger -p 6 -t $NAME "$1"
}

_error() {
  logger -p 3 -t $NAME "$1"
}

parse_config_main() {
  local section_name="$1"
  local redir_port dns_port dns_remote_addr dns_local_addr worker_count socks_port http_port
  local sed_args=""

  config_get redir_port "$section_name" redir_port
  config_get dns_port "$section_name" dns_port
  config_get dns_remote_addr "$section_name" dns_remote_addr
  config_get dns_local_addr "$section_name" dns_local_addr
  config_get worker_count "$section_name" worker_count
  config_get socks_port "$section_name" socks_port
  config_get http_port "$section_name" http_port

  [ "$redir_port" != "$TPROXY_PORT" ] && TPROXY_PORT=$redir_port
  [ "$dns_port" != "$DNS_PORT" ] && DNS_PORT=$dns_port

  if [ "$socks_port" != "0" ]; then
    sed_args="$sed_args -e s/\"{socks_disabled}\"/false/g -e s/\"{socks_port}\"/${socks_port}/g"
  else
    sed_args="$sed_args -e s/\"{socks_disabled}\"/true/g -e s/\"{socks_port}\"/1080/g"
  fi

  if [ "$http_port" != "0" ]; then
    sed_args="$sed_args -e s/\"{http_disabled}\"/false/g -e s/\"{http_port}\"/${http_port}/g"
  else
    sed_args="$sed_args -e s/\"{http_disabled}\"/true/g -e s/\"{http_port}\"/1081/g"
  fi

  sed -i $sed_args \
      -e "s/\"{redir_port}\"/${redir_port}/g" \
      -e "s/\"{dns_port}\"/${dns_port}/g" \
      -e "s/\"{dns_remote_addr}\"/\"${dns_remote_addr}\"/g" \
      -e "s/\"{dns_local_addr}\"/\"${dns_local_addr}\"/g" \
      -e "s/\"{worker_count}\"/${worker_count}/g" \
      "$CONF_DIR/config.json"
}

SERVER_LIST_STR=""

parse_config_server() {
  local section_name="$1"
  local server server_port password method enabled

  config_get server "$section_name" server
  config_get server_port "$section_name" server_port
  config_get password "$section_name" password
  config_get method "$section_name" method
  config_get enabled "$section_name" enabled

  if [ "${enabled}" = '1' ]; then
    if echo "$server" | grep -qE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
      SERVER_LIST_V4="$SERVER_LIST_V4 ${server},"
    elif echo "$server" | grep -qE '^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{1,4}$'; then
      SERVER_LIST_V6="$SERVER_LIST_V6 ${server},"
    else
      echo "Unrecognized IP format $server"
    fi

    [ -n "${SERVER_LIST_STR}" ] && SERVER_LIST_STR="${SERVER_LIST_STR},\n"
    
    SERVER_LIST_STR="${SERVER_LIST_STR}{\n"
    SERVER_LIST_STR="${SERVER_LIST_STR}      \"server\": \"${server}\",\n"
    SERVER_LIST_STR="${SERVER_LIST_STR}      \"server_port\": ${server_port},\n"
    SERVER_LIST_STR="${SERVER_LIST_STR}      \"password\": \"${password}\",\n"
    SERVER_LIST_STR="${SERVER_LIST_STR}      \"method\": \"${method}\"\n"
    SERVER_LIST_STR="${SERVER_LIST_STR}    }"
  fi
}

generate_config_json() {
  cp "$CONF_DIR/config-template.json" "$CONF_DIR/config.json"
  config_foreach parse_config_main main
  config_foreach parse_config_server server
  sed -i "s|\"{servers_list}\"|${SERVER_LIST_STR}|g" "$CONF_DIR/config.json"
}

clear_route() {
  while ip -4 rule del fwmark 0x1 table 803 2>/dev/null; do :; done
  ip -4 route del local 0.0.0.0/0 dev lo table 803 2>/dev/null || true

  while ip -6 rule del fwmark 0x1 table 803 2>/dev/null; do :; done
  ip -6 route del local ::/0 dev lo table 803 2>/dev/null || true
}

config_route() {
  clear_route

  ip -4 rule add fwmark 0x1 table 803
  ip -4 route add local 0.0.0.0/0 dev lo table 803

  ip -6 rule add fwmark 0x1 table 803
  ip -6 route add local ::/0 dev lo table 803
}

update_nftables() {
  if nft list tables | grep -q shadowproxy-mangle; then
    nft delete table inet shadowproxy-mangle
  fi
  
  nft -f /etc/shadowproxy/shadowproxy.nft -Dtproxy_port=${TPROXY_PORT}
  
  for item in $(grep -vE '^$|^#' /etc/shadowproxy/bypass_ipset.acl); do
    if echo "$item" | grep -qE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
      SERVER_LIST_V4="$SERVER_LIST_V4 ${item},"
    elif echo "$item" | grep -qE '^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{1,4}$'; then
      SERVER_LIST_V6="$SERVER_LIST_V6 ${item},"
    else
      echo "Unrecognized IP format $item"
    fi
  done

  SERVER_LIST_V4="${SERVER_LIST_V4%,}"
  SERVER_LIST_V6="${SERVER_LIST_V6%,}"

  if [ -n "${SERVER_LIST_V4}" ]; then
    nft add element inet shadowproxy-mangle whitelist_v4_set { ${SERVER_LIST_V4} }
  fi
  if [ -n "${SERVER_LIST_V6}" ]; then
    nft add element inet shadowproxy-mangle whitelist_v6_set { ${SERVER_LIST_V6} }
  fi
}

update_proxy_domains() {
  _info "Updating custom proxy domains..."
  cp -f "$CONF_DIR/shadowproxy-dns-base.acl" "$CONF_DIR/shadowproxy-dns.acl"

  if [ -f "/etc/shadowproxy/proxy_domains.acl" ]; then
    grep -vE '^$|^#' /etc/shadowproxy/proxy_domains.acl | sed 's/^/||/' > /tmp/custom_proxy_temp.txt
    
    sed -i -e '/{proxy_domains}/r /tmp/custom_proxy_temp.txt' -e '/{proxy_domains}/d' "$CONF_DIR/shadowproxy-dns.acl"
    
    rm -f /tmp/custom_proxy_temp.txt
  else
    _info "/etc/shadowproxy/proxy_domains.acl not found, skipping."
  fi
}

start_shadowproxy() {
  procd_open_instance shadowproxy
  procd_set_param command /usr/bin/sslocal -c /etc/shadowproxy/config.json
  procd_set_param file /etc/shadowproxy/config.json
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-2}
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param limits nofile="51200 51200"
  procd_close_instance
}

start_service() {
  _info "start shadowproxy service."
  
  if [ "${ENABLED}" = "0" ]; then
    _info "service shadowproxy not enabled"
    return 0
  fi

  if [ -z "$(command -v /usr/bin/sslocal)" ]; then
    _error "/usr/bin/sslocal is not exist, please install it."
    return 1
  fi

  generate_config_json

  if [ -z "${SERVER_LIST_STR}" ]; then
    _info "no enabled server, exit"
    return 1
  fi

  config_route
  update_nftables
  update_proxy_domains
  start_shadowproxy
}

stop_service() {
  _info "stop shadowproxy service."

  if nft list tables | grep -q shadowproxy-mangle; then
    nft delete table inet shadowproxy-mangle
  fi
  
  clear_route
}

service_triggers() {
  procd_add_reload_trigger "shadowproxy"
  procd_add_interface_trigger "interface.*" "wan" /etc/init.d/shadowproxy restart
  procd_add_interface_trigger "interface.*" "wwan" /etc/init.d/shadowproxy restart
}


